### ISSUE TITLE
Оптимизация AlternativeDeliveryStrategy для работы с PickPoint

### ISSUE THREAD

**Issue by Wwwoper** [Wwwoper/EasyPostLabel#3]
## Текущее поведение

Сейчас класс `AlternativeDeliveryStrategy` обрабатывает все не-почтовые доставки как альтернативные, хотя фактически работает только с центрами выдачи PickPoint. Это создает:

1. Неявную логику обработки данных
2. Потенциальные проблемы при добавлении новых способов доставки
3. Избыточный код для обработки только PickPoint доставок
4. Неточное именование компонентов

## Предлагаемые изменения

1. Переименовать `AlternativeDeliveryStrategy` в `PickPointDeliveryStrategy`
2. Выделить специфичную для PickPoint логику:
   - Обработка центров выдачи
   - Форматирование бирок
   - Создание списков доставки

3. Добавить валидацию данных PickPoint:
   - Валидация выбранного пункта выдачи:
     - Проверка корректного наименования пункта выдачи

4. Обновить конфигурацию:
   ```yaml
   delivery_strategies:
     pickpoint:
       validation:
         center_name: 
           allowed_values: ["pickpoint"]  # Список разрешенных значений
       output:
         filename: "pickpoint_delivery_list.xlsx"
         templates:
           label: "PickPoint"  # Формат бирки для доставки
   ```

## Почему это нужно

1. Улучшение читаемости и поддерживаемости кода
2. Упрощение добавления новых способов доставки
3. Более точное отражение бизнес-логики
4. Снижение риска ошибок при обработке данных

## Примечания

- Необходимо сохранить обратную совместимость с текущим форматом выходных файлов
- Рекомендуется добавить тесты для новой логики валидации
- Документировать новый формат конфигурации
- Обновить примеры использования в README.md
